### ISSUE TITLE
Missing plugin Exception

### ISSUE THREAD

**Issue by Mounikareddymouni** [bizz84/image-picker-demo-flutter#3]
MissingPluginException(No implementation found for method pickImage on channel com.musevisions.flutter/imagePicker)

**Comment by cuongdnq2710** [comment]
I clone this repository and run this bug too!

**Comment by shadyshrif** [comment]
@bizz84 Cloud you please review it and merge it to the master.

**Comment by bizz84** [comment]
@shadyshrif done. Please note that this was an example project to show how to use platform channels, so it was deliberately not using the official image picker plugin.

**Comment by bizz84** [comment]
Thanks for contributing everyone!
